language: scala
scala: 2.12.8
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "vJZnh9Z5GJ24oAXfGPTwjVc1gPcFmWu2PiQshaRmgeCWOHv+aTIUdbmRgUEeSbqxwRc2eS/+4Lz5qe+XIg4MfdTvI55njw8Wa9/G/VXAcA42Z37MDZ2vKJoRRZtMiqtb86evANeoP5jwpXjuaw9kAhdLI6xkSkXrkGlOshAaSKg2NSkLofU9GYWCt9fGBAhG9mlNqjkCtUSk1cb+xBzKJOrUFWYeHAXPhX32SkTIZ95MCQo1rPq0OKMNQbx74dQygukbzooIru3Za9S+6m+2OdPRmZoJ423E9w5P1uxANg6xb6NgvKWfiuNDjo8UAhWYssmc47UzAjD1DXQIQ5Gg9gN39EbiZfslNEIgQjcnGVTTTXKoZnTKTh1SYaVSb4KO9SwUWsuaXIXUb36dVnEpG8veBr5JErYPz1hAhcVWOqhekQVfa+eau6uYn0uovvtQ5JmbnhjSTBawNJfFJJeZO4X6HTaKRB86Hz2SkxyNhNCsmO8ml/uktZsIGJrfrfadBzA/FhNy9YE+yPftqopkV+L3p9KKXwybEdGYWiMd6LLxmZRnZ+w507PhlV3HzlKKzN642wrynPlIon3KTY3so+dx81cShkd84iLZuTdxa1hUxYIi85jdEZ4GQB6WpVmPxBkEN6f+456Lc3C7K/h34PI3oXveiEjI3rCsjgX+jkw="
    # GITHUB_TOKEN
    - secure: "TjgpfNIfUDmhWTSA95EjHr2rrHQgBPNTm42VQC8X3a4r1lTfZbxOdFfyL7DqM+KjU4YcXKvSpKz7qZ/1RR8vhQkZ1MjHEA/m9jydVS3JVkit8R37i8BX/FxUrX5PQjO/WQTEdXALzu5WjSlRYAexNUpKqmSGEfZMt2c/PRuqptFuMamZHI3VDamLvp8jzIv3LR+EOUjPF1rZHkDivDXgizPUAXu2PgU20I13eMe+Ctn43jzGJSnvLMkbeCGWKzhP0gqUWDdaxylk/hZXShXqsv9FBo1AwSu/l6+rDAAWpQ4FIFDnfdbNCHC8Btk+6WDcItQmHpvIDT1Ji/Mo6SdUpduI2StOlLiohdv0y2QfXGODJ6ONbfEBN7rjcWMO/HwNUnnaxxCX5Y7p8wHjTUZEAgY1XBfY6peUlc8OlNThrr8/RijcUVmr5ZZ7M60QmvsdDKfSH6rRK59aeJug7z+EjFLmj2hDmIJeVYITrH7HQQT99vXhIz81n9CCa1sQlbX+Ktc36Qn97u7K7QzngHKWVL/5gXrAdzDUpu7GR/x0rJhP7dsZwrVFwAGa7Jvn/rQ4dum+KyKAxVZm7I1KAxPQvA+ugya32ItJlfr6xZkLPKexzEf/fvYC6kpDhTUaB927KhpKsfyI2hjNG+WU+wvK/5khxeQvpVBaMwTKVl1cnKk="
    # GITHUB_ACCESS_TOKEN
    - secure: "UVXyURJBAkO5pW5Y2FGFP3WPYYIiwU+5hUi6tGaL060qHNjcI/L0jXfKLlJL4kG6Y7TuphD2OhcvBNt8J/zaAWLMMbJbvxWHOlGEqtyMfPf/OjKLTxGi2xDve0+Z83k7Bt21EVaJgpdNN7mfroHongC6mQJQmp6GAGwT4aEYRD+NB12T+0/qOtItXBrdAN3CgGTyf3nDH3lMWki28lSDGOO8/vaTABzYJS/47hw0lVrGoZukDEiKXEMnhfpNUt7ROqtLeemtXbznvFXEc0psKiaPfQ1UBMkt0vWcReh5ScaujyNw3MMFICUMgIOmD6TVWDaWyjQ7P0B6qVkyM45jhtVwHSSwHn7PV3bnv6U/yt9dFqCJDkIKIzi4ZpJ1JbsmiJaCoIvTJQShz4uUcPMFaovgVEre/awCWOruhq3y+DIOlBk99ljjBpowIXO4hTgf5vAM85OgE2ngKIqyZuDqd2hgI3a/RipEtBDqAMvfNZ+hWUbloiabjNesuzO9bem4vFCTqAGXcN8AjirsMq2OMGTjiWuai25mRSWYeoUUfPL1ucHZnDy1LI/psykQzEJAc1hDjU6AXeyO6dZCZvvrOWZMJzBwAKR8JtEzpiyTvtlNjewxtpWEyFURciRm69//Gri15303nS+8WiOdJgvN0k2PPm2zYeI/WVeD2uAA/3Y="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "RSFYHWmWpfKCtR1dkwwmJ6lLvWaKPPMXF0EKa66tfUEybe17U4QdMX9iGMUl1KCEOj/5Sd+h2W9j4iA5OVl+pXZqcLDGt9amorx7nabKw8tcwgDDqHax6U6I4ogny/talOkQjq8UFSqEm4V+JXuL5mr0os4DkAkjjUqyTteYaq7WSA9JUzpbX2P6YgYksF00R6XWEw5nVKGa9GdAzMZXjN0RutfeJ8hwt2wSkr/bLtVmC9Kl9adp+3grqiSn5Qq2ooPZsaIdzmVFHSzH/PxMA6h/UoRqOQhxhazS8i5xI7ij+mmxDzOrewCx/GgrUSXrY941ng2MPcMnO3A7RcYw0ic0UzABx9w6CM20057OEbJn2Y6TRITuGiP7Oy3FX3brjChV+0Ye3n3Q0NaWwXZnHyDo0k6Grb5fPYALwWqikF6EjWYJUa4N+SYotZfZGpkV6BFIRsLOlvg08FlnXEGPcYq0pS6YxViqiR/K5KU5rN4EkL5Ip8woYO5M8XIoJk7f18/GI9UWyrx6rsjms+/iIuuT9bZR/F4SN/YEJDoaECSeuY1t3FUud105eEiaXj9Lgb0j2dxZs8pqlqb2AxeMBRd/nQ9Frp4Y6TIdvvMiKV3HZe23Ja9q7YsmfAGTF7XM9w8nbpJZ3ZV/JsHU4G3kHJHYkQlxmvKZLCKZW+Gi3Ns="
    # key for gbqAuthFile.json ($key_828a0c5dfd)
    - secure: "iA/U94xG2tAgbdmBHgdq08f0CQ5zoiWWPuRM2krQrx3CaMI8Ldq6qUYlG5vN7o8wuAhLyzxGS5QTNSO66jVeW/1wXOVmuSHFx0UuOiKQWsLqUuSTNDsGZx6zmnnWe33fp4NOrNOBfujdHuweowAOI698Eoc5eCU7b9WhiW+2wTabosEA1ss9gdsNtW58ec6dIUyXq0+9/T/u6U9G6aZu/Q40sc9lb/EfingxHReu1wwVjvMZPpk5GmXFi5QRlu/2Qzf17AAZ/2f1N59UiBBM2K54pYZAPIqUjf/aF7uRzZHr4HomZxH+8Kl4bdPk4COHJDJWrL8ckOTSzE5a3bn6vgJeCxVyK/Nme+MbpaZGd0pqtXwMqArX5af8igFTcqRaWXnLb2UrCWefcMUOi24yqjJ8ShEI6ZIoy04uq12JXsTS3pr3vKCy98NuBevbNszCdZYmtPUUJuXzEzwYdjNiulfCZ0pV0gOAtU8YPd8iikcNaulsbEb18evZ0fNqKIq2R51MwQO6fBOSHVWMi9ER9x8etjnZaGl6RG6yc5T5MvLZZ1r28EvCkxLlO8cdc4/00kzvGXHrwGFEaoZxnnMo/B7LlgkGiopjmdU2BFaGUgvuYdoyC0Anb8dYG9r/9OQhRvciBV5aa9B/Ha6alqzutkTgrAZnaFaToIMeGnfMwbQ="
    # initialization vector for gbqAuthFile.json ($iv_828a0c5dfd)
    - secure: "VwMtVaqdKsEKg9hanwMOu7wi34yGD3Z74Z/YRqjmNE9bXXM45t8q+DLzZucXvJ1k3+DfkN0w730LlkHgOkVYXchK6zRntNDDnaz/rdimIje2NxGtPj+jy81gOrmZ8nHkNFUIuqWIQ+lRVv/78LEnRjHiIPUrxLBx31v0FofPyzAD0AHIxsV0F3x4595iBWPdGqXg4iGojWZ0e1U9Hu9GF4GRBBHErbu++TE4JmOcTXzsflKW7eNJ3r26VdA14hldzmyKPw5yvW+DQQj+uWi0X3PeKBddsrmm7qjICkp5dZhWM6Aha3mvtrGzNaTuj9AL7TlqY+YqmkfaRBr/ZsrzycwUQRywJi0qkbmPvlbzVM8bnUgPek13Mgm3ZObfR4RYIVobWtrvx6fxjmAyfsJ+VpYMPE6B2JzLd3v+VGIuPWIeDvkErp+p2wUR92i5hbcQgbcX+feOBkhjYReoZvG909nBWsc493L3YVMlrHLGvUZ7A1AsSgp45stUqg3mWRFgEhh9JPbizdeqNLVGj4HLm0Biy2XjvyoG+jbvC1kR073YJcmLJzkK/Y7h/bPmfYHZ6X+PTUIw6Fd1XxnD65qAzxWTN6IljCNg6L1CVKhUgT/vMdeZJ2cHw80p3gGzrSbpquIKB50NyXY7ea97p3VqSnaIOsoUJbhLEL0kEQV7kJk="

before_install:
  - sudo service ntp stop
  - sudo ntpd -gq
  - sudo service ntp start
  - mkdir core/src/test/resources
  - 'openssl aes-256-cbc -K $key_828a0c5dfd -iv $iv_828a0c5dfd -in "scripts/gbqAuthFile.json.enc" -out "core/src/test/resources/gbqAuthFile.json" -d'
  - |-
    if [ $(openssl sha1 "core/src/test/resources/gbqAuthFile.json" | egrep -o "[0-9a-f]+\$") != 4907a27c33866adffb2c0a31a374f3f242d83554 ]; then
      echo "File gbqAuthFile.json.enc failed to decrypt."
      exit 1
    else
      echo "File gbqAuthFile.json.enc successfully decrypted."
    fi

install:
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-gbq';
      fi

after_success:
  - rm -rf core/src/test/resource/gbqAuthFile.json
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - rm -rf core/src/test/resource/gbqAuthFile.json
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -delete
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -delete
