language: scala
scala: 2.12.8
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "vJZnh9Z5GJ24oAXfGPTwjVc1gPcFmWu2PiQshaRmgeCWOHv+aTIUdbmRgUEeSbqxwRc2eS/+4Lz5qe+XIg4MfdTvI55njw8Wa9/G/VXAcA42Z37MDZ2vKJoRRZtMiqtb86evANeoP5jwpXjuaw9kAhdLI6xkSkXrkGlOshAaSKg2NSkLofU9GYWCt9fGBAhG9mlNqjkCtUSk1cb+xBzKJOrUFWYeHAXPhX32SkTIZ95MCQo1rPq0OKMNQbx74dQygukbzooIru3Za9S+6m+2OdPRmZoJ423E9w5P1uxANg6xb6NgvKWfiuNDjo8UAhWYssmc47UzAjD1DXQIQ5Gg9gN39EbiZfslNEIgQjcnGVTTTXKoZnTKTh1SYaVSb4KO9SwUWsuaXIXUb36dVnEpG8veBr5JErYPz1hAhcVWOqhekQVfa+eau6uYn0uovvtQ5JmbnhjSTBawNJfFJJeZO4X6HTaKRB86Hz2SkxyNhNCsmO8ml/uktZsIGJrfrfadBzA/FhNy9YE+yPftqopkV+L3p9KKXwybEdGYWiMd6LLxmZRnZ+w507PhlV3HzlKKzN642wrynPlIon3KTY3so+dx81cShkd84iLZuTdxa1hUxYIi85jdEZ4GQB6WpVmPxBkEN6f+456Lc3C7K/h34PI3oXveiEjI3rCsjgX+jkw="
    # GITHUB_TOKEN
    - secure: "TjgpfNIfUDmhWTSA95EjHr2rrHQgBPNTm42VQC8X3a4r1lTfZbxOdFfyL7DqM+KjU4YcXKvSpKz7qZ/1RR8vhQkZ1MjHEA/m9jydVS3JVkit8R37i8BX/FxUrX5PQjO/WQTEdXALzu5WjSlRYAexNUpKqmSGEfZMt2c/PRuqptFuMamZHI3VDamLvp8jzIv3LR+EOUjPF1rZHkDivDXgizPUAXu2PgU20I13eMe+Ctn43jzGJSnvLMkbeCGWKzhP0gqUWDdaxylk/hZXShXqsv9FBo1AwSu/l6+rDAAWpQ4FIFDnfdbNCHC8Btk+6WDcItQmHpvIDT1Ji/Mo6SdUpduI2StOlLiohdv0y2QfXGODJ6ONbfEBN7rjcWMO/HwNUnnaxxCX5Y7p8wHjTUZEAgY1XBfY6peUlc8OlNThrr8/RijcUVmr5ZZ7M60QmvsdDKfSH6rRK59aeJug7z+EjFLmj2hDmIJeVYITrH7HQQT99vXhIz81n9CCa1sQlbX+Ktc36Qn97u7K7QzngHKWVL/5gXrAdzDUpu7GR/x0rJhP7dsZwrVFwAGa7Jvn/rQ4dum+KyKAxVZm7I1KAxPQvA+ugya32ItJlfr6xZkLPKexzEf/fvYC6kpDhTUaB927KhpKsfyI2hjNG+WU+wvK/5khxeQvpVBaMwTKVl1cnKk="
    # GITHUB_ACCESS_TOKEN
    - secure: "UVXyURJBAkO5pW5Y2FGFP3WPYYIiwU+5hUi6tGaL060qHNjcI/L0jXfKLlJL4kG6Y7TuphD2OhcvBNt8J/zaAWLMMbJbvxWHOlGEqtyMfPf/OjKLTxGi2xDve0+Z83k7Bt21EVaJgpdNN7mfroHongC6mQJQmp6GAGwT4aEYRD+NB12T+0/qOtItXBrdAN3CgGTyf3nDH3lMWki28lSDGOO8/vaTABzYJS/47hw0lVrGoZukDEiKXEMnhfpNUt7ROqtLeemtXbznvFXEc0psKiaPfQ1UBMkt0vWcReh5ScaujyNw3MMFICUMgIOmD6TVWDaWyjQ7P0B6qVkyM45jhtVwHSSwHn7PV3bnv6U/yt9dFqCJDkIKIzi4ZpJ1JbsmiJaCoIvTJQShz4uUcPMFaovgVEre/awCWOruhq3y+DIOlBk99ljjBpowIXO4hTgf5vAM85OgE2ngKIqyZuDqd2hgI3a/RipEtBDqAMvfNZ+hWUbloiabjNesuzO9bem4vFCTqAGXcN8AjirsMq2OMGTjiWuai25mRSWYeoUUfPL1ucHZnDy1LI/psykQzEJAc1hDjU6AXeyO6dZCZvvrOWZMJzBwAKR8JtEzpiyTvtlNjewxtpWEyFURciRm69//Gri15303nS+8WiOdJgvN0k2PPm2zYeI/WVeD2uAA/3Y="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "RSFYHWmWpfKCtR1dkwwmJ6lLvWaKPPMXF0EKa66tfUEybe17U4QdMX9iGMUl1KCEOj/5Sd+h2W9j4iA5OVl+pXZqcLDGt9amorx7nabKw8tcwgDDqHax6U6I4ogny/talOkQjq8UFSqEm4V+JXuL5mr0os4DkAkjjUqyTteYaq7WSA9JUzpbX2P6YgYksF00R6XWEw5nVKGa9GdAzMZXjN0RutfeJ8hwt2wSkr/bLtVmC9Kl9adp+3grqiSn5Qq2ooPZsaIdzmVFHSzH/PxMA6h/UoRqOQhxhazS8i5xI7ij+mmxDzOrewCx/GgrUSXrY941ng2MPcMnO3A7RcYw0ic0UzABx9w6CM20057OEbJn2Y6TRITuGiP7Oy3FX3brjChV+0Ye3n3Q0NaWwXZnHyDo0k6Grb5fPYALwWqikF6EjWYJUa4N+SYotZfZGpkV6BFIRsLOlvg08FlnXEGPcYq0pS6YxViqiR/K5KU5rN4EkL5Ip8woYO5M8XIoJk7f18/GI9UWyrx6rsjms+/iIuuT9bZR/F4SN/YEJDoaECSeuY1t3FUud105eEiaXj9Lgb0j2dxZs8pqlqb2AxeMBRd/nQ9Frp4Y6TIdvvMiKV3HZe23Ja9q7YsmfAGTF7XM9w8nbpJZ3ZV/JsHU4G3kHJHYkQlxmvKZLCKZW+Gi3Ns="
    # GBQ_DECRYPT_PASSWORD
    #- secure: "jSBAaIaqc5M2jhh0DEYkfFh5Ax0ytxJwSmoN21jeZxPW2EhZoG6GyFGAIt4oE9cyS284vSL0JzR9MlVb+xR4tEDgC7cXDCowWNWxV476fFuCOjZ3wTYsTkpgCRmMcPSR3xsQouqkLOh5AFXul9CsaPXv451jYNsRnpxBYh3ACHd89cJ3iT1aGem++8k/HhMEkLsGbsYhCtmPYPPPrYuGyl1atE4yjLyznzVjYVeaQ+CFoetUmw1CYHwKtYhGdoRV4drXThVS60xCiByCBd69SZ6uco2PnVc6H5QlzyPhxVF6NGwC/7EJ/kCxVKohexjyfM2E9WU5UGb9bj73Q3GC/ezn3TNYkjRD78OdPzj+XTpq34qwVzr+psTp8Z80TqginW+3FhjV6Atga9Mn2Z1V3an3qZCglMhUn7XHCmO8+TZz2dRraFo+uIIHjs46iu+nrXbAACbdObH2RtjgXW1TpIJgx/lXu4eupp6EvP5sHJM5Uo3Ki/QXgL+LIjUB2v4rgAeaoBls9jTkHb7mUR2Kq5prrNbUxaChjv2ruZUVz+5v+1rw8sJ7GCMdcALPBy/q9AgLOWq6KmUP7h5Y2Fn1Igu0ikVMR45JjNVCAGPHk/tDS6zWimGmZkdU8620YgGTTvcMM8HyQd01w9LcBHBPnycPnFG+IZZ4aFrMeEywqZg="
    # key for gbq-enc-private.key ($key_d499630087)
    #- secure: "mkQQeVmG/sZ7uQqWzTn5wzM/bWZ5n6xcvWnpbxoqoPGg5Rt0eTD+nFvxxPKLIO37RQiUOiZCQ10yCd73t8m7AyOdJZNdLItr/tQ41IFlAHXO4eZW6VvJZcYPUQPWBxztL9dynp5rGN+ftYJPDfXBavbKdEwXpkyiLSB6wnWnI4nsJfDmXWi/Co4yn8F4geQW8EilHV+f3WKPkqXa+9/mLnX69OYyYDObJifDkTmv7K11WAmHUTyDt5jGZHMUO2phVAKmnpHC2a8Y0H/WkjFpPJltjRUNfAWnz9BEyZ0qDbFouA/oJranEghNLOAVRoyXJAvJhkqS714hZ+Uh1NEEheVWFAQOZ5r+U8KEXIhvNb4NhQtv3Lx0cnidxG47k8s4yEn+eG9jyY7+THk1BFap9aQFGqKS12PyI0L81uDQLQpBXaLb7rlBaF9JXg8sy9poUggfKWtdOqYPSf6sQPtqnTofN9SEfHyaeh6HgqGOCHbGdIRiGHoaCclbZ5VItbbqYy5tm29jP4rrzVmZxwkDQq5msEplE19txzFvVElNbBbibKOTAritRIE2rQ7um+jXeFjF8BjQPhB7ptszN1qwIOMJg09qlgfQ1oHkS3dY3N1K8kneOcPkhE8Pjy2sPcSyCmIBlvFMVPesoyUUnjryq625Q3q4ScqMNsIoxmIni7k="
    # initialization vector for gbq-enc-private.key ($iv_d499630087)
    #- secure: "mL+jKuoWikjoOh0ix9O5IJ97v4lBDAUVYtaANocNMpHKyiUXhmqgQjF1C6xw8TFDx/GsYw7sP8jVS6ATbaUV1kXKWvpEW1/4iDnZsLnZTwQb5ZaVrDsA8Yn1J2lhPUtXbWgNz8K3tjXWYQHWTzoS4z2dTcdudj7mvl+CuiAm0rHwD3noCQTVGtFKvhOJMf59iBseitGWWDDP3mDhbFsC5mmDi4OU4rR+UITWrFV/1qgMeEm3CDpwiPpLbHqPc95qAkCLY0B8WYP5PUwTsYFCzRrKPOSOSONYP9wOmOZz/EQm5xGx+MQX9fg2Ke/J7COFQP5n+NIC7PuBV+hVZV0pKjpbDMPfCkJll/E+c6QP06kAZYZK9s23QwuwQnx91xzmx+zO6omAF2yO+QIyqzrchjCln+hGycTzOqRFzP0TqlQS0PnoARO38ChLHwHF3gHHPmQNNDiwPy6vpMr14aBD13KJzgkDF7UDit+qsA85uLAdYm4NzO/4Di+dclK/r936ZkiWcWh3RcfMewKIURG07/LPTCKPBBkreczLvyaiSqmVwU3BiWNuKLmRs1lG+YwSlJ7Yx14Zi1pRi0tF1bT/RH5RT//gMaUEH5P3SMfXev7PgqzOdXZ17kC4QKPiJnX6CbddunqEMxiUBtH52v/FRPdl2eNbhUn2oscaSTfj4IY="
    # key for gbqAuthFile.json ($key_828a0c5dfd)
    - secure: "iA/U94xG2tAgbdmBHgdq08f0CQ5zoiWWPuRM2krQrx3CaMI8Ldq6qUYlG5vN7o8wuAhLyzxGS5QTNSO66jVeW/1wXOVmuSHFx0UuOiKQWsLqUuSTNDsGZx6zmnnWe33fp4NOrNOBfujdHuweowAOI698Eoc5eCU7b9WhiW+2wTabosEA1ss9gdsNtW58ec6dIUyXq0+9/T/u6U9G6aZu/Q40sc9lb/EfingxHReu1wwVjvMZPpk5GmXFi5QRlu/2Qzf17AAZ/2f1N59UiBBM2K54pYZAPIqUjf/aF7uRzZHr4HomZxH+8Kl4bdPk4COHJDJWrL8ckOTSzE5a3bn6vgJeCxVyK/Nme+MbpaZGd0pqtXwMqArX5af8igFTcqRaWXnLb2UrCWefcMUOi24yqjJ8ShEI6ZIoy04uq12JXsTS3pr3vKCy98NuBevbNszCdZYmtPUUJuXzEzwYdjNiulfCZ0pV0gOAtU8YPd8iikcNaulsbEb18evZ0fNqKIq2R51MwQO6fBOSHVWMi9ER9x8etjnZaGl6RG6yc5T5MvLZZ1r28EvCkxLlO8cdc4/00kzvGXHrwGFEaoZxnnMo/B7LlgkGiopjmdU2BFaGUgvuYdoyC0Anb8dYG9r/9OQhRvciBV5aa9B/Ha6alqzutkTgrAZnaFaToIMeGnfMwbQ="
    # initialization vector for gbqAuthFile.json ($iv_828a0c5dfd)
    - secure: "VwMtVaqdKsEKg9hanwMOu7wi34yGD3Z74Z/YRqjmNE9bXXM45t8q+DLzZucXvJ1k3+DfkN0w730LlkHgOkVYXchK6zRntNDDnaz/rdimIje2NxGtPj+jy81gOrmZ8nHkNFUIuqWIQ+lRVv/78LEnRjHiIPUrxLBx31v0FofPyzAD0AHIxsV0F3x4595iBWPdGqXg4iGojWZ0e1U9Hu9GF4GRBBHErbu++TE4JmOcTXzsflKW7eNJ3r26VdA14hldzmyKPw5yvW+DQQj+uWi0X3PeKBddsrmm7qjICkp5dZhWM6Aha3mvtrGzNaTuj9AL7TlqY+YqmkfaRBr/ZsrzycwUQRywJi0qkbmPvlbzVM8bnUgPek13Mgm3ZObfR4RYIVobWtrvx6fxjmAyfsJ+VpYMPE6B2JzLd3v+VGIuPWIeDvkErp+p2wUR92i5hbcQgbcX+feOBkhjYReoZvG909nBWsc493L3YVMlrHLGvUZ7A1AsSgp45stUqg3mWRFgEhh9JPbizdeqNLVGj4HLm0Biy2XjvyoG+jbvC1kR073YJcmLJzkK/Y7h/bPmfYHZ6X+PTUIw6Fd1XxnD65qAzxWTN6IljCNg6L1CVKhUgT/vMdeZJ2cHw80p3gGzrSbpquIKB50NyXY7ea97p3VqSnaIOsoUJbhLEL0kEQV7kJk="

before_install:
  - sudo ntpdate ntp.ubuntu.com
  - mkdir core/src/test/resources
  - 'openssl aes-256-cbc -K $key_828a0c5dfd -iv $iv_828a0c5dfd -in "scripts/gbqAuthFile.json.enc" -out "core/src/test/resources/gbqAuthFile.json" -d'
  - |-
    if [ $(openssl sha1 "core/src/test/resources/gbqAuthFile.json" | egrep -o "[0-9a-f]+\$") != 4907a27c33866adffb2c0a31a374f3f242d83554 ]; then
      echo "File gbqAuthFile.json.enc failed to decrypt."
      exit 1
    else
      echo "File gbqAuthFile.json.enc successfully decrypted."
    fi

install:
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-gbq';
      fi

after_success:
  - rm -rf core/src/test/resource/gbqAuthFile.json
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - rm -rf core/src/test/resource/gbqAuthFile.json
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -delete
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -delete
