language: scala
scala: 2.12.8
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "vJZnh9Z5GJ24oAXfGPTwjVc1gPcFmWu2PiQshaRmgeCWOHv+aTIUdbmRgUEeSbqxwRc2eS/+4Lz5qe+XIg4MfdTvI55njw8Wa9/G/VXAcA42Z37MDZ2vKJoRRZtMiqtb86evANeoP5jwpXjuaw9kAhdLI6xkSkXrkGlOshAaSKg2NSkLofU9GYWCt9fGBAhG9mlNqjkCtUSk1cb+xBzKJOrUFWYeHAXPhX32SkTIZ95MCQo1rPq0OKMNQbx74dQygukbzooIru3Za9S+6m+2OdPRmZoJ423E9w5P1uxANg6xb6NgvKWfiuNDjo8UAhWYssmc47UzAjD1DXQIQ5Gg9gN39EbiZfslNEIgQjcnGVTTTXKoZnTKTh1SYaVSb4KO9SwUWsuaXIXUb36dVnEpG8veBr5JErYPz1hAhcVWOqhekQVfa+eau6uYn0uovvtQ5JmbnhjSTBawNJfFJJeZO4X6HTaKRB86Hz2SkxyNhNCsmO8ml/uktZsIGJrfrfadBzA/FhNy9YE+yPftqopkV+L3p9KKXwybEdGYWiMd6LLxmZRnZ+w507PhlV3HzlKKzN642wrynPlIon3KTY3so+dx81cShkd84iLZuTdxa1hUxYIi85jdEZ4GQB6WpVmPxBkEN6f+456Lc3C7K/h34PI3oXveiEjI3rCsjgX+jkw="
    # GITHUB_TOKEN
    - secure: "TjgpfNIfUDmhWTSA95EjHr2rrHQgBPNTm42VQC8X3a4r1lTfZbxOdFfyL7DqM+KjU4YcXKvSpKz7qZ/1RR8vhQkZ1MjHEA/m9jydVS3JVkit8R37i8BX/FxUrX5PQjO/WQTEdXALzu5WjSlRYAexNUpKqmSGEfZMt2c/PRuqptFuMamZHI3VDamLvp8jzIv3LR+EOUjPF1rZHkDivDXgizPUAXu2PgU20I13eMe+Ctn43jzGJSnvLMkbeCGWKzhP0gqUWDdaxylk/hZXShXqsv9FBo1AwSu/l6+rDAAWpQ4FIFDnfdbNCHC8Btk+6WDcItQmHpvIDT1Ji/Mo6SdUpduI2StOlLiohdv0y2QfXGODJ6ONbfEBN7rjcWMO/HwNUnnaxxCX5Y7p8wHjTUZEAgY1XBfY6peUlc8OlNThrr8/RijcUVmr5ZZ7M60QmvsdDKfSH6rRK59aeJug7z+EjFLmj2hDmIJeVYITrH7HQQT99vXhIz81n9CCa1sQlbX+Ktc36Qn97u7K7QzngHKWVL/5gXrAdzDUpu7GR/x0rJhP7dsZwrVFwAGa7Jvn/rQ4dum+KyKAxVZm7I1KAxPQvA+ugya32ItJlfr6xZkLPKexzEf/fvYC6kpDhTUaB927KhpKsfyI2hjNG+WU+wvK/5khxeQvpVBaMwTKVl1cnKk="
    # GITHUB_ACCESS_TOKEN
    - secure: "UVXyURJBAkO5pW5Y2FGFP3WPYYIiwU+5hUi6tGaL060qHNjcI/L0jXfKLlJL4kG6Y7TuphD2OhcvBNt8J/zaAWLMMbJbvxWHOlGEqtyMfPf/OjKLTxGi2xDve0+Z83k7Bt21EVaJgpdNN7mfroHongC6mQJQmp6GAGwT4aEYRD+NB12T+0/qOtItXBrdAN3CgGTyf3nDH3lMWki28lSDGOO8/vaTABzYJS/47hw0lVrGoZukDEiKXEMnhfpNUt7ROqtLeemtXbznvFXEc0psKiaPfQ1UBMkt0vWcReh5ScaujyNw3MMFICUMgIOmD6TVWDaWyjQ7P0B6qVkyM45jhtVwHSSwHn7PV3bnv6U/yt9dFqCJDkIKIzi4ZpJ1JbsmiJaCoIvTJQShz4uUcPMFaovgVEre/awCWOruhq3y+DIOlBk99ljjBpowIXO4hTgf5vAM85OgE2ngKIqyZuDqd2hgI3a/RipEtBDqAMvfNZ+hWUbloiabjNesuzO9bem4vFCTqAGXcN8AjirsMq2OMGTjiWuai25mRSWYeoUUfPL1ucHZnDy1LI/psykQzEJAc1hDjU6AXeyO6dZCZvvrOWZMJzBwAKR8JtEzpiyTvtlNjewxtpWEyFURciRm69//Gri15303nS+8WiOdJgvN0k2PPm2zYeI/WVeD2uAA/3Y="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "RSFYHWmWpfKCtR1dkwwmJ6lLvWaKPPMXF0EKa66tfUEybe17U4QdMX9iGMUl1KCEOj/5Sd+h2W9j4iA5OVl+pXZqcLDGt9amorx7nabKw8tcwgDDqHax6U6I4ogny/talOkQjq8UFSqEm4V+JXuL5mr0os4DkAkjjUqyTteYaq7WSA9JUzpbX2P6YgYksF00R6XWEw5nVKGa9GdAzMZXjN0RutfeJ8hwt2wSkr/bLtVmC9Kl9adp+3grqiSn5Qq2ooPZsaIdzmVFHSzH/PxMA6h/UoRqOQhxhazS8i5xI7ij+mmxDzOrewCx/GgrUSXrY941ng2MPcMnO3A7RcYw0ic0UzABx9w6CM20057OEbJn2Y6TRITuGiP7Oy3FX3brjChV+0Ye3n3Q0NaWwXZnHyDo0k6Grb5fPYALwWqikF6EjWYJUa4N+SYotZfZGpkV6BFIRsLOlvg08FlnXEGPcYq0pS6YxViqiR/K5KU5rN4EkL5Ip8woYO5M8XIoJk7f18/GI9UWyrx6rsjms+/iIuuT9bZR/F4SN/YEJDoaECSeuY1t3FUud105eEiaXj9Lgb0j2dxZs8pqlqb2AxeMBRd/nQ9Frp4Y6TIdvvMiKV3HZe23Ja9q7YsmfAGTF7XM9w8nbpJZ3ZV/JsHU4G3kHJHYkQlxmvKZLCKZW+Gi3Ns="
    # key for gbqAuthFile.json ($key_275ab4e00a)
    - secure: "nS0QasBvJEXivpuDKsM4q/2XrfJ7VOAKOiTtGRNpAjUfI+OoflIcjmi68gzmc2ps+Hss3l/90YJ1oKVTs2jKxwBb0KcxOPVvdWNDSrI1LVXhNiOoDEG3kCztReEf9Yu1HDO26XT9jrO7OkvmejYhsmRTojpJKFpFIMFydNE9wZxqB5ZEgoIpJpFfPizs7RMVZ1robslKtJXDwAjr2AwY0DMD245h3iblchgaPJ2EThiRSN3ybFwZ1/sab5rXxspmMwH3Fd/SbHbUYmrUr6hZ3WFbe7+4QEmpF+j7ItBVr2dunpoeDKHRoYemkug9lhBqXtNLGdpufENWEkG1640TOjKCvA/UWAmwsIpSbEFbHoSD46azmBIr1lljzOzxkWyc+AFMlyWlYKIDmwyl4joKqPdsJXZ5lMe6qYgnDg4cpn/z+vfrqUnSWcOaqCdO50u8N7hsBkBGgnFVnShmnJenzYY8HAgby+6bBT0JdAd78x3YdYiZM6Swy1FIRpb31tAOdgGJCduPNrg5EdX6epn/tcVkB1hND7jTRirMnYGmTp/BqcQt2wl9n04uE1swdEp3F4WgZDjLsgFw9gFw0APDNo5wpD/WOG/IjbzOUl3sBYEDinCRPDGF4X1ExZxvRu5gwd5UgXTIFYUjBEL2Cp72IkTSe3Z6grZbpoOU4pwpeQQ="
    # initialization vector for gbqAuthFile.json ($iv_275ab4e00a)
    - secure: "UzmJ9EyiOiW/pBRE0Mbe2Sh4hy9h4lHNlSosqTSTlr1FqGXoD+sZN2kEFoZKqOqL8plUAT2+xJiFG0T52ed5jLd5vp+RWmpHrQwWhq9iRYVXrcHOyAM/6cPZdXX5/wGrBekZBtC6q9U9ylrkPj24GSRqTSI0OkOvs7HJOJHUhKowDUlDrZXbOP5QiiEB95elmdE/MBPCAMtVbONrHh376LsWRu/BJaNRX+DxZJWks63MaNRJRdgYVOBZdORYKfroAqk5Xh9CaiA2gaEagbNvOXEIdfitrqt///VdiZYBZUZLAX+hh6jS9pla6js8ZUCBgVevXqMOK4TY3z62vKty197CFhhd0EB39TtDQcgp33z9ar6QKQQk12SejczluqMbILD9bPc4ROycEHiJHZkc/MZZHHoLqYc5oit0/Sh5H/bH2y64k3Pij2EAQxtYG/t3MZBh1bw0nJUarAAn1UgDZ49k9Fx3jh37uGSFZgV1BMO/tjQ8+S/7Te8zHg0rZaVSc3R724dipyTz+pllwuI1qT5O2BzvEc7rQr0xNdZS9gT3DAxMsaeCEMl/2s2lW1I4Cu04nz7mTVc8yCD44PEbmnEgIGjHzfM8wu9DJRFm5fGkF1h74XPtObdG/0CchhDuUWLtroGlJOAVOwJ6hHwCzpEC5v87iYf/6IIi3WrS4hA="

before_install:



before_install:
  - sudo service ntp stop
  - sudo ntpd -gq
  - sudo service ntp start
  - mkdir core/src/test/resources
  - 'openssl aes-256-cbc -K $key_275ab4e00a -iv $iv_275ab4e00a -in "scripts/gbqAuthFile.json.enc" -out "core/src/test/resources/gbqAuthFile.json" -d'
  - |-
    if [ $(openssl sha1 "core/src/test/resources/gbqAuthFile.json" | egrep -o "[0-9a-f]+\$") != ef2a9dd4591f0e20f1eb2aa4caf975a8bbd081f1 ]; then
      echo "File gbqAuthFile.json.enc failed to decrypt."
      exit 1
    else 
      echo "File gbqAuthFile.json.enc successfully decrypted."
    fi

install:
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-gbq';
      fi

after_success:
  - rm -rf core/src/test/resource/gbqAuthFile.json
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - rm -rf core/src/test/resource/gbqAuthFile.json
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -delete
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -delete
