language: scala
scala: 2.12.8
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "vJZnh9Z5GJ24oAXfGPTwjVc1gPcFmWu2PiQshaRmgeCWOHv+aTIUdbmRgUEeSbqxwRc2eS/+4Lz5qe+XIg4MfdTvI55njw8Wa9/G/VXAcA42Z37MDZ2vKJoRRZtMiqtb86evANeoP5jwpXjuaw9kAhdLI6xkSkXrkGlOshAaSKg2NSkLofU9GYWCt9fGBAhG9mlNqjkCtUSk1cb+xBzKJOrUFWYeHAXPhX32SkTIZ95MCQo1rPq0OKMNQbx74dQygukbzooIru3Za9S+6m+2OdPRmZoJ423E9w5P1uxANg6xb6NgvKWfiuNDjo8UAhWYssmc47UzAjD1DXQIQ5Gg9gN39EbiZfslNEIgQjcnGVTTTXKoZnTKTh1SYaVSb4KO9SwUWsuaXIXUb36dVnEpG8veBr5JErYPz1hAhcVWOqhekQVfa+eau6uYn0uovvtQ5JmbnhjSTBawNJfFJJeZO4X6HTaKRB86Hz2SkxyNhNCsmO8ml/uktZsIGJrfrfadBzA/FhNy9YE+yPftqopkV+L3p9KKXwybEdGYWiMd6LLxmZRnZ+w507PhlV3HzlKKzN642wrynPlIon3KTY3so+dx81cShkd84iLZuTdxa1hUxYIi85jdEZ4GQB6WpVmPxBkEN6f+456Lc3C7K/h34PI3oXveiEjI3rCsjgX+jkw="
    # GITHUB_TOKEN
    - secure: "TjgpfNIfUDmhWTSA95EjHr2rrHQgBPNTm42VQC8X3a4r1lTfZbxOdFfyL7DqM+KjU4YcXKvSpKz7qZ/1RR8vhQkZ1MjHEA/m9jydVS3JVkit8R37i8BX/FxUrX5PQjO/WQTEdXALzu5WjSlRYAexNUpKqmSGEfZMt2c/PRuqptFuMamZHI3VDamLvp8jzIv3LR+EOUjPF1rZHkDivDXgizPUAXu2PgU20I13eMe+Ctn43jzGJSnvLMkbeCGWKzhP0gqUWDdaxylk/hZXShXqsv9FBo1AwSu/l6+rDAAWpQ4FIFDnfdbNCHC8Btk+6WDcItQmHpvIDT1Ji/Mo6SdUpduI2StOlLiohdv0y2QfXGODJ6ONbfEBN7rjcWMO/HwNUnnaxxCX5Y7p8wHjTUZEAgY1XBfY6peUlc8OlNThrr8/RijcUVmr5ZZ7M60QmvsdDKfSH6rRK59aeJug7z+EjFLmj2hDmIJeVYITrH7HQQT99vXhIz81n9CCa1sQlbX+Ktc36Qn97u7K7QzngHKWVL/5gXrAdzDUpu7GR/x0rJhP7dsZwrVFwAGa7Jvn/rQ4dum+KyKAxVZm7I1KAxPQvA+ugya32ItJlfr6xZkLPKexzEf/fvYC6kpDhTUaB927KhpKsfyI2hjNG+WU+wvK/5khxeQvpVBaMwTKVl1cnKk="
    # GITHUB_ACCESS_TOKEN
    - secure: "UVXyURJBAkO5pW5Y2FGFP3WPYYIiwU+5hUi6tGaL060qHNjcI/L0jXfKLlJL4kG6Y7TuphD2OhcvBNt8J/zaAWLMMbJbvxWHOlGEqtyMfPf/OjKLTxGi2xDve0+Z83k7Bt21EVaJgpdNN7mfroHongC6mQJQmp6GAGwT4aEYRD+NB12T+0/qOtItXBrdAN3CgGTyf3nDH3lMWki28lSDGOO8/vaTABzYJS/47hw0lVrGoZukDEiKXEMnhfpNUt7ROqtLeemtXbznvFXEc0psKiaPfQ1UBMkt0vWcReh5ScaujyNw3MMFICUMgIOmD6TVWDaWyjQ7P0B6qVkyM45jhtVwHSSwHn7PV3bnv6U/yt9dFqCJDkIKIzi4ZpJ1JbsmiJaCoIvTJQShz4uUcPMFaovgVEre/awCWOruhq3y+DIOlBk99ljjBpowIXO4hTgf5vAM85OgE2ngKIqyZuDqd2hgI3a/RipEtBDqAMvfNZ+hWUbloiabjNesuzO9bem4vFCTqAGXcN8AjirsMq2OMGTjiWuai25mRSWYeoUUfPL1ucHZnDy1LI/psykQzEJAc1hDjU6AXeyO6dZCZvvrOWZMJzBwAKR8JtEzpiyTvtlNjewxtpWEyFURciRm69//Gri15303nS+8WiOdJgvN0k2PPm2zYeI/WVeD2uAA/3Y="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "RSFYHWmWpfKCtR1dkwwmJ6lLvWaKPPMXF0EKa66tfUEybe17U4QdMX9iGMUl1KCEOj/5Sd+h2W9j4iA5OVl+pXZqcLDGt9amorx7nabKw8tcwgDDqHax6U6I4ogny/talOkQjq8UFSqEm4V+JXuL5mr0os4DkAkjjUqyTteYaq7WSA9JUzpbX2P6YgYksF00R6XWEw5nVKGa9GdAzMZXjN0RutfeJ8hwt2wSkr/bLtVmC9Kl9adp+3grqiSn5Qq2ooPZsaIdzmVFHSzH/PxMA6h/UoRqOQhxhazS8i5xI7ij+mmxDzOrewCx/GgrUSXrY941ng2MPcMnO3A7RcYw0ic0UzABx9w6CM20057OEbJn2Y6TRITuGiP7Oy3FX3brjChV+0Ye3n3Q0NaWwXZnHyDo0k6Grb5fPYALwWqikF6EjWYJUa4N+SYotZfZGpkV6BFIRsLOlvg08FlnXEGPcYq0pS6YxViqiR/K5KU5rN4EkL5Ip8woYO5M8XIoJk7f18/GI9UWyrx6rsjms+/iIuuT9bZR/F4SN/YEJDoaECSeuY1t3FUud105eEiaXj9Lgb0j2dxZs8pqlqb2AxeMBRd/nQ9Frp4Y6TIdvvMiKV3HZe23Ja9q7YsmfAGTF7XM9w8nbpJZ3ZV/JsHU4G3kHJHYkQlxmvKZLCKZW+Gi3Ns="   

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-gbq';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -delete
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -delete
